apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "fabric.fullname" . }}-ca
  labels:
    {{- include "fabric.labels" . | nindent 4 }}
    app.kubernetes.io/component: ca
spec:
  replicas: {{ .Values.ca.replicas }}
  selector:
    matchLabels:
      {{- include "fabric.selectorLabels" . | nindent 6 }}
      app.kubernetes.io/component: ca
  template:
    metadata:
      labels:
        {{- include "fabric.selectorLabels" . | nindent 8 }}
        app.kubernetes.io/component: ca
    spec:
      containers:
        - name: ca
          image: "{{ .Values.ca.image.repository }}:{{ .Values.ca.image.tag }}"
          imagePullPolicy: {{ .Values.ca.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.ca.service.port }}
          env:
            - name: FABRIC_CA_SERVER_TLS_ENABLED
              value: "true"
            - name: FABRIC_CA_SERVER_CA_BOOTSTRAP_USER
              value: {{ .Values.ca.admin.user | quote }}
            - name: FABRIC_CA_SERVER_CA_BOOTSTRAP_PASS
              value: {{ .Values.ca.admin.password | quote }}
          command: ["sh", "-c"]
          args:
            - 'fabric-ca-server start -b "$FABRIC_CA_SERVER_CA_BOOTSTRAP_USER:$FABRIC_CA_SERVER_CA_BOOTSTRAP_PASS" -d'
