###############################################################################
#
# Copyright IBM Corp. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
###############################################################################

###############################################################################
#
# Peer section
#
###############################################################################
peer:
  id: peer
  networkId: dev
  listenAddress: 0.0.0.0:7051
  chaincodeListenAddress: 0.0.0.0:7052
  address: peer.example.com:7051
  addressAutoDetect: false
  gomaxprocs: -1
  keepalive:
    minInterval: 60s
    client:
      interval: 60s
      timeout: 20s
    deliveryClient:
      interval: 60s
      timeout: 20s
  gossip:
    bootstrap: []
    useLeaderElection: true
    orgLeader: false
    endpoint: ""
    maxBlockCountToStore: 100
    maxPropagationBurstLatency: 10ms
    maxPropagationBurstSize: 10
    propagateIterations: 1
    propagatePeerNum: 3
    pullInterval: 4s
    pullPeerNum: 3
    requestStateInfoInterval: 4s
    publishCertPeriod: 10s
    publishStateInfoInterval: 4s
    stateInfoRetentionInterval:
    skipBlockVerification: false
    dialTimeout: 3s
    connTimeout: 2s
    recvBuffSize: 20
    sendBuffSize: 200
    digestWaitTime: 1s
    requestWaitTime: 1s
    responseWaitTime: 2s
    aliveTimeInterval: 5s
    aliveExpirationTimeout: 25s
    reconnectInterval: 25s
    externalEndpoint: ""
    election:
      startupGracePeriod: 15s
      membershipSampleInterval: 1s
      leaderAliveThreshold: 10s
      leaderElectionDuration: 5s
  tls:
    enabled: true
    clientAuthRequired: false
    cert:
      file: ""
    key:
      file: ""
    rootcert:
      file: ""
    serverhostoverride:
  authentication:
    timewindow: 15m
  fileSystemPath: /var/hyperledger/production
  BCCSP:
    Default: SW
    SW:
      Hash: SHA2
      Security: 256
      FileKeyStore:
        KeyStore:
  mspConfigPath: msp
  localMspId: OrgMSP
  profile:
    enabled: false
    listenAddress: 0.0.0.0:6060
  handlers:
    authFilters:
      - name: DefaultAuth
      - name: ExpirationCheck
    decoratorFilters:
      - name: DefaultDecorator
    endorsers:
      escc:
        name: DefaultEndorsement
    validators:
      vscc:
        name: DefaultValidation
  validatorPoolSize:
  discovery:
    enabled: true
    authCacheEnabled: true
    authCacheMaxSize: 1000
    authCachePurgeRetentionRatio: 0.75
    orgMembersAllowedAccess: false
  limits:
    concurrency:
      endorserService: 2500
      deliverService: 2500
    gatewayService:
      readTimeOut: 300s
      writeTimeOut: 300s

###############################################################################
#
# VM section
#
###############################################################################
vm:
  endpoint: unix:///host/var/run/docker.sock
  docker:
    tls:
      enabled: false
      ca:
        file: docker/ca.crt
      cert:
        file: docker/tls.crt
      key:
        file: docker/tls.key
    attachStdout: false
    hostConfig:
      NetworkMode: host
      LogConfig:
        Type: json-file
        Config:
          max-size: "50m"
          max-file: "5"
      Memory: 2147483648
  chaincodeHost: ""

###############################################################################
#
# Chaincode section
#
###############################################################################
chaincode:
  builder: hyperledger/fabric-ccenv:latest
  pull: false
  golang:
    runtime: hyperledger/fabric-baseos:latest
    dynamicLink: false
  java:
    runtime: hyperledger/fabric-javaenv:latest
  node:
    runtime: hyperledger/fabric-nodeenv:latest
  installTimeout: 300s
  startuptimeout: 300s
  executetimeout: 30s
  mode: net
  keepalive: 0
  system:
    _lifecycle: enable
    cscc: enable
    lscc: enable
    qscc: enable
  logging:
    level: info
    shim: warning
    format: "%{color}%{time:2006-01-02 15:04:05.000 MST} [%{module}] %{shortfunc} -> %{level:.4s} %{id:03x}%{color:reset} %{message}"
  externalBuilders: []

###############################################################################
#
# Ledger section
#
###############################################################################
ledger:
  blockchain:
  state:
    stateDatabase: goleveldb
    totalQueryLimit: 100000
    couchDBConfig:
      couchDBAddress: 127.0.0.1:5984
      username:
      password:
      maxRetries: 3
      maxRetriesOnStartup: 10
      requestTimeout: 35s
      internalQueryLimit: 1000
      maxBatchUpdateSize: 1000
      createGlobalChangesDB: false
      cacheSize: 64
  history:
    enableHistoryDatabase: true

###############################################################################
#
# Operations section
#
###############################################################################
operations:
  listenAddress: 127.0.0.1:9443
  tls:
    enabled: false
    cert:
      file:
    key:
      file:
    clientAuthRequired: false
    clientRootCAs:
      files: []

###############################################################################
#
# Metrics section
#
###############################################################################
metrics:
  provider: disabled
  statsd:
    network: udp
    address: 127.0.0.1:8125
    prefix: server
    writeInterval: 10s
  prometheus:
    handlerPath: /metrics
    tls:
      enabled: false
      cert:
        file:
    client:
      ca:
        file:

###############################################################################
#
# Consul section
#
###############################################################################
consul:
  service:
    enabled: false
  host: 127.0.0.1:8500
  token: ""
  register: true
  check: ""
  deregisterafter: 1m
  heartbeat: 10s
  tls:
    enabled: false
    cert:
      file: tls/server.crt
    key:
      file: tls/server.key
    ca:
      file: tls/ca.crt
  authentication:
    enabled: false
    authfile: consul.auth

###############################################################################
#
# ACL configuration
#
###############################################################################
acl:
  enableACLs: true
  adminPolicy:
    resourcePolicyType: TOKEN
    adminPolicyName:
  resources:
    _lifecycle:
      policy: /Channel/Application/Writers
    lscc:
      policy: /Channel/Application/Writers
    qscc:
      policy: /Channel/Application/Readers
    cscc:
      policy: /Channel/Application/Admins

###############################################################################
#
# Resource configuration
#
###############################################################################
resources:
  resources:
    resources:
      default:
        limit:
          memory: 2048Mi
        reservation:
          memory: 1024Mi
