apiVersion: hlf.kungfusoftware.es/v1alpha1
kind: FabricFollowerChannel
metadata:
  name: follower-mychannel-org1
spec:
  anchorPeers:
  - host: peer0-org1.hlf
    port: 7051
  externalPeersToJoin:
  - url: grpcs://peer0-org1.hlf:7051
    tlsCACert: '-----BEGIN CERTIFICATE-----

      MIICRTCCAeugAwIBAgIQafDRYoo6TMDiwH9PNDVDXzAKBggqhkjOPQQDAjBtMQsw

      CQYDVQQGEwJFUzERMA8GA1UEBxMIQWxpY2FudGUxETAPBgNVBAkTCEFsaWNhbnRl

      MRkwFwYDVQQKExBLdW5nIEZ1IFNvZnR3YXJlMQ0wCwYDVQQLEwRUZWNoMQ4wDAYD

      VQQDEwV0bHNjYTAeFw0yNjA3MTYwNzE5MTBaFw0zNjA3MTcwNzE5MTBaMG0xCzAJ

      BgNVBAYTAkVTMREwDwYDVQQHEwhBbGljYW50ZTERMA8GA1UECRMIQWxpY2FudGUx

      GTAXBgNVBAoTEEt1bmcgRnUgU29mdHdhcmUxDTALBgNVBAsTBFRlY2gxDjAMBgNV

      BAMTBXRsc2NhMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEigNrtxYL4CfBsHgJ

      SrQnH/tPdTZ8NwSpqJu8mz7AomQOKwEUT5ZWjdbdvm05tGD+ZTW1ETGdDpkDP4LI

      w60SbqNtMGswDgYDVR0PAQH/BAQDAgGmMB0GA1UdJQQWMBQGCCsGAQUFBwMCBggr

      BgEFBQcDATAPBgNVHRMBAf8EBTADAQH/MCkGA1UdDgQiBCD1+Mllq+zRcruTXfwb

      w9DO1Pgg7J3+ivA8aiQwKds44DAKBggqhkjOPQQDAgNIADBFAiAlQIHGl/NWam+m

      BJlXAsFyhUR64fcGF1S5IW2HMWPvawIhAL0jH6eXFk8uzNGPHntt/HdoRCCtzC5p

      GZADSjiNMvj2

      -----END CERTIFICATE-----'
  hlfIdentity:
    secretKey: user.yaml
    secretName: org1-admin
    secretNamespace: hlf
  mspId: Org1MSP
  name: mychannel
  orderers:
  - certificate: '-----BEGIN CERTIFICATE-----

      MIIDHDCCAsKgAwIBAgIUGa4ALI+61sxkR9FLO296KXhm0K4wCgYIKoZIzj0EAwIw

      bTELMAkGA1UEBhMCRVMxETAPBgNVBAcTCEFsaWNhbnRlMREwDwYDVQQJEwhBbGlj

      YW50ZTEZMBcGA1UEChMQS3VuZyBGdSBTb2Z0d2FyZTENMAsGA1UECxMEVGVjaDEO

      MAwGA1UEAxMFdGxzY2EwHhcNMjYwNzE2MDcxOTEwWhcNMjcwNzE4MDIzMzAwWjAk

      MRAwDgYDVQQLEwdvcmRlcmVyMRAwDgYDVQQDEwdvcmRlcmVyMFkwEwYHKoZIzj0C

      AQYIKoZIzj0DAQcDQgAEchBWDV/amBr7cXQh48F1u8zErvVr+l/7lk/NXZnb/LaR

      9f22y2vQcULGFp38mLABUFeZHPRaSKmQsbh4GmdrtKOCAYcwggGDMA4GA1UdDwEB

      /wQEAwIDqDAdBgNVHSUEFjAUBggrBgEFBQcDAQYIKwYBBQUHAwIwDAYDVR0TAQH/

      BAIwADAdBgNVHQ4EFgQUNlJept0E/WuNbrJVWsH1NGRUI+4wKwYDVR0jBCQwIoAg

      gbLfy6AFpqwJfcexqRcWzvJsTh76g2Hul7N9oyD+GRgwgZoGA1UdEQSBkjCBj4IJ

      bG9jYWxob3N0gghvcmRlcmVyMIIMb3JkZXJlcjAuaGxmghNvcmRlcmVyMC5sb2Nh

      bGhvLnN0ghlhZG1pbi1vcmRlcmVyMC5sb2NhbGhvLnN0ghNvcmRlcmVyMC5sb2Nh

      bGhvLnN0ghlhZG1pbi1vcmRlcmVyMC5sb2NhbGhvLnN0hwR/AAABhwSsFgACMFsG

      CCoDBAUGBwgBBE97ImF0dHJzIjp7ImhmLkFmZmlsaWF0aW9uIjoiIiwiaGYuRW5y

      b2xsbWVudElEIjoib3JkZXJlciIsImhmLlR5cGUiOiJvcmRlcmVyIn19MAoGCCqG

      SM49BAMCA0gAMEUCIQDcLp4w5kNTaxw3RkkQ9kbshjyqSlzTgXyCWms282ksFQIg

      D1JuJZJB8VOehhlaz4W+vJzQGM4x6z2IamJH+xu5UQk=

      -----END CERTIFICATE-----'
    url: grpcs://orderer0.hlf:7050
  peersToJoin: []
  revocationList: null
