prometheus:
  enabled: true
  image:
    repository: prom/prometheus
    tag: v2.53.0
    pullPolicy: IfNotPresent
  service:
    port: 9090
  retention: 30d
  scrapeInterval: 15s

loki:
  enabled: true
  image:
    repository: grafana/loki
    tag: "3.0.0"
    pullPolicy: IfNotPresent
  service:
    port: 3100

grafana:
  enabled: true
  image:
    repository: grafana/grafana
    tag: "11.0.0"
    pullPolicy: IfNotPresent
  service:
    port: 3000
  admin:
    user: admin
    password: admin

ingress:
  enabled: true
  className: nginx
  annotations: {}
  hosts:
    grafana: grafana.example.com
  tls: []
