global:
  storageClass: ""
  imagePullSecrets: []

fabricVersion: "2.5.15"
caVersion: "1.5.5"

orderer:
  enabled: true
  replicas: 1
  image:
    repository: hyperledger/fabric-orderer
    tag: "2.5.15"
    pullPolicy: IfNotPresent
  service:
    port: 7050
    adminPort: 7053
    operationsPort: 9443
  persistence:
    enabled: true
    size: 10Gi
  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 250m
      memory: 512Mi

peers:
  replicas: 3
  image:
    repository: hyperledger/fabric-peer
    tag: "2.5.15"
    pullPolicy: IfNotPresent
  service:
    port: 7051
    chaincodePort: 7052
    operationsPort: 9443
  persistence:
    enabled: true
    size: 20Gi
  resources:
    limits:
      cpu: "2"
      memory: 2Gi
    requests:
      cpu: 500m
      memory: 1Gi

couchdb:
  replicas: 3
  image:
    repository: couchdb
    tag: "3.3"
    pullPolicy: IfNotPresent
  service:
    port: 5984
  auth:
    username: admin
    password: adminpw
  persistence:
    enabled: true
    size: 20Gi

ca:
  replicas: 4
  image:
    repository: hyperledger/fabric-ca
    tag: "1.5.5"
    pullPolicy: IfNotPresent
  service:
    port: 7054
  admin:
    user: admin
    password: adminpw
  persistence:
    enabled: true
    size: 5Gi

postgres:
  replicas: 4
  image:
    repository: postgres
    tag: "16-alpine"
    pullPolicy: IfNotPresent
  service:
    port: 5432
  auth:
    user: fabric
    password: fabric
  persistence:
    enabled: true
    size: 10Gi
